"""add user_channels

Revision ID: 69b68d48fda1
Revises: adcea46954b8
Create Date: 2026-10-08 18:10:25.349337

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b68d48fda1'
down_revision: Union[str, None] = 'adcea46954b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channels',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("platform IN ('telegram','eitaa')", name='ck_user_channels_platform'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_user_channels_user_url')
    )
    with op.batch_alter_table('user_channels', schema=None) as batch_op:
        batch_op.create_index('ix_user_channels_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_channels', schema=None) as batch_op:
        batch_op.drop_index('ix_user_channels_user_id')

    op.drop_table('user_channels')
    # ### end Alembic commands ###
