"""add reminders, reminder_notifications and notification_logs

Revision ID: 8707cb6e187f
Revises: b3d3d6c5bf65
Create Date: 2026-10-04 21:59:37.570961

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8707cb6e187f'
down_revision: Union[str, None] = 'b3d3d6c5bf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('related_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("notification_type IN ('REMINDER','ANNOUNCEMENT','BROADCAST')", name='ck_notification_logs_notification_type'),
    sa.CheckConstraint("status IN ('SENT','FAILED')", name='ck_notification_logs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index('ix_notification_logs_related', ['notification_type', 'related_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_user_id'), ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reminder_datetime', sa.DateTime(), nullable=False),
    sa.Column('repeat_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("repeat_type IN ('NONE','DAILY','WEEKLY','MONTHLY')", name='ck_reminders_repeat_type'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_reminders_reminder_datetime', ['reminder_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('reminder_notifications',
    sa.Column('reminder_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_offset', sa.String(length=16), nullable=False),
    sa.Column('fire_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("alert_offset IN ('AT_TIME','HOURS_1','DAYS_1')", name='ck_reminder_notifications_alert_offset'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id', 'alert_offset', 'fire_datetime', name='uq_reminder_notifications_occurrence')
    )
    with op.batch_alter_table('reminder_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_notifications_due', ['is_sent', 'fire_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_notifications_reminder_id'), ['reminder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_notifications_reminder_id'))
        batch_op.drop_index('ix_reminder_notifications_due')

    op.drop_table('reminder_notifications')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_index('ix_reminders_reminder_datetime')
        batch_op.drop_index(batch_op.f('ix_reminders_course_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_user_id'))
        batch_op.drop_index('ix_notification_logs_related')

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
