"""add university_links

Revision ID: 9872b21078f7
Revises: 40bbe636b0de
Create Date: 2026-10-04 22:43:46.725036

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9872b21078f7'
down_revision: Union[str, None] = '40bbe636b0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_links',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("url LIKE 'http://%' OR url LIKE 'https://%'", name='ck_university_links_url_scheme'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university_links', schema=None) as batch_op:
        batch_op.create_index('ix_university_links_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_links', schema=None) as batch_op:
        batch_op.drop_index('ix_university_links_user_id')

    op.drop_table('university_links')
    # ### end Alembic commands ###
