"""add grade_items kind

Revision ID: adcea46954b8
Revises: 8d20aa2d75e9
Create Date: 2026-10-06 17:01:40.140328

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcea46954b8'
down_revision: Union[str, None] = '8d20aa2d75e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), server_default='OTHER', nullable=False))
        batch_op.create_check_constraint(
            'ck_grade_items_kind',
            "kind IN ('HOMEWORK','QUIZ','MIDTERM','FINAL','PROJECT','OTHER')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_items', schema=None) as batch_op:
        batch_op.drop_constraint('ck_grade_items_kind', type_='check')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
