"""add weekly_schedules

Revision ID: b37bc974aa3e
Revises: b0e95f17be96
Create Date: 2026-10-04 21:33:56.714149

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37bc974aa3e'
down_revision: Union[str, None] = 'b0e95f17be96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_schedules',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=False),
    sa.Column('file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_schedules_user_id', ['user_id'], unique=False)
        batch_op.create_index('uq_weekly_schedules_active_user', ['user_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active IS TRUE'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedules', schema=None) as batch_op:
        batch_op.drop_index('uq_weekly_schedules_active_user', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active IS TRUE'))
        batch_op.drop_index('ix_weekly_schedules_user_id')

    op.drop_table('weekly_schedules')
    # ### end Alembic commands ###
