"""add grade_items

Revision ID: b3d3d6c5bf65
Revises: 75c57cf86947
Create Date: 2026-10-04 21:47:05.738495

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d3d6c5bf65'
down_revision: Union[str, None] = '75c57cf86947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_items',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_grade_items_max_score_positive'),
    sa.CheckConstraint('score <= max_score', name='ck_grade_items_score_lte_max'),
    sa.CheckConstraint('score >= 0', name='ck_grade_items_score_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_items_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_items_course_id'))

    op.drop_table('grade_items')
    # ### end Alembic commands ###
