"""announcements table

Revision ID: ded7b70453a2
Revises: 9872b21078f7
Create Date: 2026-10-04 23:12:02.814541

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded7b70453a2'
down_revision: Union[str, None] = '9872b21078f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("file_type IS NULL OR file_type IN ('photo','document')", name='ck_announcements_file_type'),
    sa.CheckConstraint("source IN ('telegram','eitaa')", name='ck_announcements_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('ix_announcements_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('ix_announcements_user_id')

    op.drop_table('announcements')
    # ### end Alembic commands ###
